" Init Pathogen
set nocompatible
execute pathogen#infect()
syntax on
filetype plugin indent on


" Vundle Plugins
"call vundle#begin()

"Plugin 'VundleVim/Vundle.vim'
"Plugin 'scrooloose/nerdtree'
"Plugin 'kien/ctrlp.vim'
"Plugin 'bling/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'
"Plugin 'majutsushi/tagbar'
"Plugin 'airblade/vim-gitgutter'
"Plugin 'leafgarland/typescript-vim'

" Python stuff
"Plugin 'davidhalter/jedi-vim'

"call vundle#end()            " required

" Config
let g:molokai_original = 1
syntax enable
colorscheme molokai
set number
set ts=4
set autoindent
set expandtab
set shiftwidth=4
set cursorline
set showmatch
let python_highlight_all = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='powerlineish'
set hidden
set nofoldenable
set mouse=a

" Keybindings
noremap <Tab> :NERDTreeToggle<cr>
noremap <C-Q> :TagbarToggle<cr>
noremap <C-T> :enew<cr>
noremap <C-W> :bd<cr>
noremap <C-Right> :bnext<cr>
noremap <C-Left> :bprevious<cr>
