" Init Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

" Vundle Plugins
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'klen/python-mode'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'majutsushi/tagbar'
Plugin 'airblade/vim-gitgutter'


call vundle#end()            " required
filetype plugin indent on    " required

" Config
syntax enable
set number
set ts=4
set autoindent
set expandtab
set shiftwidth=4
set cursorline
set showmatch
let python_highlight_all = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='powerlineish'
set hidden

" Keybindings
noremap <Tab> :NERDTreeToggle<cr>
noremap <C-Q> :TagbarToggle<cr>
noremap <C-T> :enew<cr>
noremap <C-W> :bd<cr>
noremap <C-Right> :bnext<cr>
noremap <C-Left> :bprevious<cr>
